/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the complete application configuration */
        get: operations["ConfigAPI_getConfig"];
        /** @description Update the complete application configuration */
        put: operations["ConfigAPI_updateConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/ezbeq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get EzBEQ configuration */
        get: operations["ConfigAPI_getEzbeqConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/hdmi-sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get HDMI sync configuration */
        get: operations["ConfigAPI_getHdmiSyncConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/homeassistant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get Home Assistant configuration */
        get: operations["ConfigAPI_getHaConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/main": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get main configuration */
        get: operations["ConfigAPI_getMainConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/player": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get player configuration */
        get: operations["ConfigAPI_getPlayerConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Complete application configuration */
        AppConfig: {
            /** @description EzBEQ integration settings */
            ezbeq: components["schemas"]["EZBEQConfig"];
            /** @description Home Assistant integration settings */
            homeAssistant: components["schemas"]["HomeAssistantConfig"];
            /** @description Media player settings */
            player: components["schemas"]["PlayerConfig"];
            /** @description Main application settings */
            main: components["schemas"]["MainConfig"];
            /** @description HDMI sync settings */
            hdmiSync: components["schemas"]["HDMISyncConfig"];
        };
        /** @description EzBEQ integration configuration */
        EZBEQConfig: {
            /**
             * Format: int64
             * @description Database ID (internal use only)
             */
            readonly id?: number;
            /**
             * @description Adjust master volume with profile
             * @default true
             */
            adjustMasterVolumeWithProfile: boolean;
            /**
             * @description Denon AVR IP address
             * @default
             * @example 192.168.1.100
             */
            denonIP: string;
            /**
             * @description Denon AVR port
             * @default 23
             * @example 23
             */
            denonPort: string;
            /**
             * @description Enable dry run mode (no actual changes)
             * @default false
             */
            dryRun: boolean;
            /**
             * @description Enable EzBEQ integration
             * @default false
             */
            enabled: boolean;
            /**
             * @description Enable TV BEQ profiles
             * @default false
             */
            enableTVBEQ: boolean;
            /**
             * @description Send notification when profile is loaded
             * @default false
             */
            notifyOnLoad: boolean;
            /**
             * @description Send notification when profile is unloaded
             * @default false
             */
            notifyOnUnload: boolean;
            /**
             * @description Preferred BEQ author
             * @default
             * @example aron7awol
             */
            preferredAuthor: string;
            /**
             * @description MiniDSP slot numbers
             * @default []
             */
            slots: number[];
            /**
             * @description Stop Plex playback if BEQ profile doesn't match
             * @default false
             */
            stopPlexIfMismatch: boolean;
            /**
             * @description EzBEQ server port
             * @default 8080
             * @example 8080
             */
            port: string;
            /**
             * @description EzBEQ server hostname or IP address
             * @default ezbeq.local
             * @example ezbeq.local
             */
            url: string;
            /**
             * @description Connection protocol
             * @default http
             * @enum {string}
             */
            scheme: "http" | "https";
            /**
             * @description Use AVR codec search for BEQ profiles
             * @default false
             */
            useAVRCodecSearch: boolean;
            /**
             * @description AVR brand (Denon, Marantz, etc.)
             * @default Denon
             * @example Denon
             */
            avrBrand: string;
            /**
             * @description AVR API URL
             * @default
             * @example http://192.168.1.100
             */
            avrURL: string;
            /**
             * @description Enable loose edition matching
             * @default false
             */
            looseEditionMatching: boolean;
            /**
             * @description Skip edition matching entirely
             * @default false
             */
            skipEditionMatching: boolean;
        };
        /** @description HDMI sync configuration */
        HDMISyncConfig: {
            /**
             * Format: int64
             * @description Database ID (internal use only)
             */
            readonly id?: number;
            /**
             * @description Enable HDMI sync
             * @default false
             */
            enabled: boolean;
            /**
             * @description HDMI source input
             * @default
             * @example HDMI1
             */
            source: string;
            /**
             * @description Sync timing in milliseconds
             * @default 500
             * @example 500
             */
            time: string;
            /**
             * @description Envy device identifier
             * @default
             */
            envy: string;
            /**
             * @description Media player IP address
             * @default
             * @example 192.168.1.50
             */
            playerIP: string;
            /**
             * @description Media player machine identifier
             * @default
             * @example abc123def456
             */
            playerMachineIdentifier: string;
            /**
             * @description Connection protocol
             * @default http
             * @enum {string}
             */
            scheme: "http" | "https";
        };
        /** @description Home Assistant integration configuration */
        HomeAssistantConfig: {
            /**
             * Format: int64
             * @description Database ID (internal use only)
             */
            readonly id?: number;
            /**
             * @description Enable Home Assistant integration
             * @default false
             */
            enabled: boolean;
            /**
             * @description Remote entity name in Home Assistant
             * @default
             * @example remote.shield_tv
             */
            remoteEntityName: string;
            /**
             * Format: password
             * @description Home Assistant authentication token
             * @default
             */
            token: string;
            /**
             * @description Trigger aspect ratio change on media events
             * @default false
             */
            triggerAspectRatioChangeOnEvent: boolean;
            /**
             * @description Notification endpoint name
             * @default
             * @example notify.tv
             */
            notifyEndpointName: string;
            /**
             * Format: int32
             * @description Notification display time in milliseconds
             * @default 5000
             */
            notifyDisplayTime: number;
            /**
             * @description Home Assistant URL
             * @default
             * @example homeassistant.local
             */
            url: string;
            /**
             * @description Home Assistant port
             * @default 8123
             * @example 8123
             */
            port: string;
            /**
             * @description Connection protocol
             * @default http
             * @enum {string}
             */
            scheme: "http" | "https";
        };
        /** @description Main application configuration */
        MainConfig: {
            /**
             * Format: int64
             * @description Database ID (internal use only)
             */
            readonly id?: number;
            /**
             * @description Port for the webhook server to listen on
             * @default 9999
             * @example 9999
             */
            listenPort: string;
        };
        /**
         * @description Supported media player types
         * @enum {string}
         */
        Player: "Plex" | "Jellyfin" | "HomeAssistant";
        /** @description Media player configuration */
        PlayerConfig: {
            /**
             * Format: int64
             * @description Database ID (internal use only)
             */
            readonly id?: number;
            /**
             * @description Type of media player
             * @default Plex
             */
            playerType: components["schemas"]["Player"];
            /**
             * Format: password
             * @description Authentication token for the media player
             * @default
             */
            token: string;
            /**
             * @description User ID for players that require it
             * @default
             * @example 123456789
             */
            userID: string;
            /**
             * @description Media player URL
             * @default
             * @example plex.local
             */
            url: string;
            /**
             * @description Media player port
             * @default 32400
             * @example 32400
             */
            port: string;
            /**
             * @description Connection protocol
             * @default http
             * @enum {string}
             */
            scheme: "http" | "https";
            /**
             * @description Filter by device UUID (comma-separated for multiple)
             * @default
             * @example abc123,def456
             */
            deviceUUIDFilter: string;
            /**
             * @description Filter by owner name
             * @default
             * @example John Doe
             */
            ownerNameFilter: string;
            /**
             * @description Skip TMDB metadata lookup (Jellyfin only)
             * @default false
             */
            skipTMDB: boolean;
            /**
             * @description Media entity name (Home Assistant only)
             * @default
             * @example media_player.living_room
             */
            mediaEntityName: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ConfigAPI_getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfig"];
                };
            };
        };
    };
    ConfigAPI_updateConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppConfig"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfig"];
                };
            };
        };
    };
    ConfigAPI_getEzbeqConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EZBEQConfig"];
                };
            };
        };
    };
    ConfigAPI_getHdmiSyncConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HDMISyncConfig"];
                };
            };
        };
    };
    ConfigAPI_getHaConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeAssistantConfig"];
                };
            };
        };
    };
    ConfigAPI_getMainConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MainConfig"];
                };
            };
        };
    };
    ConfigAPI_getPlayerConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerConfig"];
                };
            };
        };
    };
}
