repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1 # Consider updating if a newer stable tag is available
    hooks:
      - id: go-mod-tidy
      - id: go-fumpt
        args: [-l, -w]
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.4.0
    hooks:
      - id: golangci-lint
        args: [--fix, --config=.golangci.yml]
