version: '3.8' 

services:
  plex-webhook-automation:
    image: gowatchit-local
    ports:
      - '9999:9999' 
      - '3000:3000'
    environment: 
      LOG_LEVEL: 'debug'
      LOG_FILE: 'true'
      BASE_DIR: '/data'
    volumes:
      - ./docker/data/:/data 